Create 2023-05-29-Qubit.md
1712n/dni-website pull request #38
Opened 2023-05-29 14:45 UTC by L0nest

A new article has been added to the "post" directory. The article is about hacking Qubit Finance in 2022.

2023-05-31 15:43 UTC, eric-oconnor approved these changes
Well-rounded article with easily verifiable facts from multiple sources.

2023-05-31 16:20 UTC, evgenydmitriev requested changes

2023-05-31 16:20 UTC, evgenydmitriev commented on content/attacks/posts/2023-05-29-Qubit.md
> +---
add all required headers

2023-05-31 16:20 UTC, evgenydmitriev commented on content/attacks/posts/2023-05-29-Qubit.md
> +A huge amount of xETH was issued, used as collateral, and took about $80 million worth of tokens from the pool.
use specific numbers, avoid words like "huge"

2023-05-31 16:20 UTC, evgenydmitriev commented on content/attacks/posts/2023-05-29-Qubit.md
> +## Timeline
timeline needs to be a timeline, not one event

2023-05-31 16:20 UTC, evgenydmitriev commented on content/attacks/posts/2023-05-29-Qubit.md
> +## Lessons Learned From The Attack
don't create any non-standard section not found in other articles

2023-05-31 16:20 UTC, evgenydmitriev commented on content/attacks/posts/2023-05-29-Qubit.md
> +## Additional Details
don't create any non-standard section not found in other articles

2023-05-31 16:20 UTC, evgenydmitriev commented on content/attacks/posts/2023-05-29-Qubit.md
> +## Attackers
add theories, description of their sophistication, anything that can help to narrow the suspect pool

2023-06-02 13:16 UTC, evgenydmitriev commented
/qualitycheck

2023-06-02 14:50 UTC, L0nest commented
/qualitycheck

2023-06-02 14:54 UTC, evgenydmitriev commented
/qualitycheck

(only wiki reviewers can trigger the quality check)

2023-06-02 15:12 UTC, evgenydmitriev approved these changes

2023-06-02 15:12 UTC, evgenydmitriev commented on content/attacks/posts/2023-05-29-Qubit.md
> +title: Hackers Breach Qubit Finance Platform, Stealing $80 Million
Quotes are needed since there are special characters in the title

2023-06-02 15:12 UTC, merged

2023-06-08 15:43 UTC, danisztls commented
@jhirschkorn can you comment `/payout` here to test the automation? AFAIK @albina-at-inca already paid the author.

2023-06-08 18:25 UTC, jhirschkorn commented
/payout